name: split
description: The game 'Split' by Team amonia created during the flame game jam 2022
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flame: ^1.3.0
  mini_sprite: ^0.0.1
  flame_mini_sprite: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.1.2
  flutter_test:
    sdk: flutter
